- .gitignore
- README.md
- Vagrantfile
- saltstack/pillar/common/init.sls
- saltstack/pillar/custom/example.sls
- saltstack/pillar/top.sls
- saltstack/salt/common/init.sls
> Custom pillar

- README.md
- saltstack/salt/common/init.sls
- saltstack/salt/common/r.sls
- saltstack/salt/top.sls
> Move R installation to separate state

- README.md
- Vagrantfile
- saltstack/pillar/common/init.sls
- saltstack/pillar/custom/example.sls
- saltstack/salt/common/bbs.sls
- saltstack/salt/common/init.sls
- saltstack/salt/top.sls
> Bbs configuration

- saltstack/salt/common/linux.sls
> Add create_users option for linux

- saltstack/pillar/common/linux.sls
- saltstack/salt/common/dirs.sls
> Rename longtests to bioc-longtests

- README.md
- saltstack/salt/common/mac.sls
> Fix mac biocbuild pass

- saltstack/salt/common/dirs.sls
> Create CRAN-style path for M1

- saltstack/salt/common/mac.sls
> Brew install pandoc for M1

- saltstack/salt/dependencies/java/init.sls
> Remove open from JAVA_HOME

- saltstack/pillar/common/linux.sls
- saltstack/salt/common/mac.sls
> Add/rename mac-arm64 builds

- saltstack/pillar/common/mac.sls
> Replace .NET 6.0 with 5.0 runtime installer URL

- saltstack/salt/common/mac.sls
> Remove bin_env to allow salt to find pip

- saltstack/salt/dependencies/reticulate_python/init.sls
- saltstack/salt/top.sls
> Add Python renderer to determine RETICULATE_PYTHON

- saltstack/pillar/common/linux.sls
- saltstack/pillar/common/mac.sls
- saltstack/salt/dependencies/dotnet/init.sls
> Update to dotnet 6.0

- saltstack/salt/rlang/linux.sls
> Add site-library

- saltstack/salt/rlang/mac.sls
> Fix misspelling that prevented symlink creation for sdk

- README.md
- saltstack/pillar/common/mac.sls
- saltstack/salt/dependencies/macfuse/init.sls
> Update macFuse, add note

- saltstack/salt/common/linux.sls
> Remove libcudart10.1

- saltstack/salt/common/mac.sls
> Remove mac update

- saltstack/salt/common/mac.sls
- saltstack/salt/rlang/mac.sls
> Change Downloads to tmp

- saltstack/pillar/common/linux.sls
- saltstack/pillar/common/mac.sls
- saltstack/salt/dependencies/quarto/init.sls
- saltstack/salt/top.sls
> Add dependency quarto

- .github/workflows/build_ghcr.yaml
- startup_bbs_standalone_devel.sh
- startup_bbs_standalone_release.sh
Hopefully addresses https://github.com/Bioconductor/bioconductor_salt/issues/131
> Fix R detection and log size

- Dockerfile
- Makes compressed image size smaller by squashing all build layers
> Squash layers

- saltstack/salt/rlang/mac.sls
> Add timeout=180 to allow sf, terra download

- startup_bbs_standalone_devel.sh
- startup_bbs_standalone_release.sh
> Fix saltstack install

- saltstack/pillar/custom/devel_standalone.sls
- saltstack/pillar/custom/release_standalone.sls
> Set release to 3.20, devel to 3.21

- .github/workflows/build_ghcr.yaml
- Dockerfile
> Build noble containers
